sudo: required

services:
  - mysql

language: java

jdk:
  - oraclejdk8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS restaurant_service;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('1111') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - mvn clean test